[build]
  command = "pnpm install --frozen-lockfile=false && cd apps/web && pnpm build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "10.12.1"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 