[build]
  command = "pnpm install && cd apps/web && pnpm build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "10.12.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 