[build]
  command = "npm install && npx turbo run build --filter @dietkem/web"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "production"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 